import { NextRequest } from "next/server";
import { mkdir, writeFile, readFile } from "fs/promises";
import path from "path";
import sharp from "sharp";
import { prisma } from "@/lib/db";
import { json } from "@/lib/api-helpers";
import { generateHowToCard } from "@/lib/generate-howto-card";

export const dynamic = "force-dynamic";
// gpt-image-2 can take up to 7 minutes; allow the full window
export const maxDuration = 300;

const STICKER_RESULTS_DIR = path.join(process.cwd(), "uploads", "players", "sticker-results");
const PACKS_DIR = path.join(process.cwd(), "uploads", "players", "sticker-packs");

const QUADRANTS = [
  { index: 1, left: 0, top: 0 },
  { index: 2, left: 512, top: 0 },
  { index: 3, left: 0, top: 512 },
  { index: 4, left: 512, top: 512 },
];

// How long a job can stay "processing" before being considered stuck
const STUCK_JOB_THRESHOLD_MS = 15 * 60 * 1000; // 15 minutes
const MAX_ATTEMPTS = 3;

function verifySecret(request: NextRequest): boolean {
  const secret = process.env.INTERNAL_CRON_SECRET;
  if (!secret) return true; // Not configured — allow (dev mode)
  const auth = request.headers.get("authorization") ?? "";
  return auth === `Bearer ${secret}`;
}

export async function POST(request: NextRequest) {
  if (!verifySecret(request)) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401 });
  }

  // ── 1. Recover stuck jobs ─────────────────────────────────────────────
  const stuckCutoff = new Date(Date.now() - STUCK_JOB_THRESHOLD_MS);
  await prisma.stickerJobQueue.updateMany({
    where: { status: "processing", updatedAt: { lt: stuckCutoff } },
    data: { status: "pending" },
  });

  // ── 2. Bail out if another job is already processing ─────────────────
  const inFlight = await prisma.stickerJobQueue.findFirst({ where: { status: "processing" } });
  if (inFlight) {
    return json({ queued: "busy", jobId: inFlight.id });
  }

  // ── 3. Pick the oldest pending job ───────────────────────────────────
  const job = await prisma.stickerJobQueue.findFirst({
    where: { status: "pending" },
    orderBy: { createdAt: "asc" },
    include: { player: true },
  });
  if (!job) {
    return json({ queued: 0 });
  }

  // Mark as processing
  await prisma.stickerJobQueue.update({
    where: { id: job.id },
    data: { status: "processing", attempts: { increment: 1 } },
  });

  const player = job.player;
  console.log(`[sticker-queue-worker] processing job ${job.id} for player ${player.id} (${player.name})`);

  try {
    // ── 4. Verify prerequisites ─────────────────────────────────────────
    if (!player.facePhotoPath) {
      throw new Error("Player has no face photo yet — will retry when face is enrolled");
    }

    const existingPack = await prisma.playerStickerPack.findFirst({ where: { playerId: player.id } });
    if (existingPack) {
      // Already generated by admin or a previous run — mark done and skip
      await prisma.stickerJobQueue.update({ where: { id: job.id }, data: { status: "done" } });
      console.log(`[sticker-queue-worker] player ${player.id} already has a pack — job marked done`);
      return json({ queued: "skipped", reason: "already_has_pack" });
    }

    // ── 5. Fetch the Pickleball prompt for the player's gender ─────────
    const template = await prisma.stickerTemplate.findFirst({ where: { name: "Pickleball" } });
    if (!template) throw new Error("Pickleball template not found in database");
    const prompt = player.gender === "male" ? template.malePrompt : template.femalePrompt;
    console.log(`[sticker-queue-worker] using ${player.gender === "male" ? "male" : "female"} prompt for player ${player.id}`);

    // ── 6. Resolve face photo path ──────────────────────────────────────
    const urlPath = player.facePhotoPath.split("?")[0];
    const imageAbsPath = path.join(process.cwd(), urlPath);

    // ── 7. WaveSpeed / gpt-image-2 generation ──────────────────────────
    if (!process.env.WAVESPEED_API_KEY) throw new Error("WAVESPEED_API_KEY is not set");

    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const WaveSpeed = require("wavespeed");
    const client = new WaveSpeed.Client();

    const isPubliclyReachable = !!process.env.RAILWAY_PUBLIC_DOMAIN;
    let imageInput: string;
    if (isPubliclyReachable) {
      const appUrl = process.env.APP_URL ?? `https://${process.env.RAILWAY_PUBLIC_DOMAIN}`;
      imageInput = `${appUrl}${imageAbsPath.replace(process.cwd(), "").replace(/\\/g, "/")}`;
    } else {
      const imageBytes = await readFile(imageAbsPath);
      const ext = path.extname(imageAbsPath).slice(1).toLowerCase() || "jpeg";
      const mime = ext === "png" ? "image/png" : ext === "webp" ? "image/webp" : "image/jpeg";
      imageInput = `data:${mime};base64,${imageBytes.toString("base64")}`;
    }

    const startTime = Date.now();
    console.log(`[sticker-queue-worker] calling WaveSpeed gpt-image-2 for player ${player.id}...`);

    const result = await client.run("openai/gpt-image-2/edit", {
      background: "opaque",
      enable_base64_output: false,
      enable_sync_mode: false,
      images: [imageInput],
      input_fidelity: "high",
      output_format: "png",
      prompt: prompt.trim(),
      quality: "medium",
      size: "1024*1024",
    });

    const elapsed = (Date.now() - startTime) / 1000;
    const outputUrl = result.outputs[0];
    if (!outputUrl) throw new Error("WaveSpeed returned no output URL");

    const imgRes = await fetch(outputUrl);
    if (!imgRes.ok) throw new Error(`Failed to download image from WaveSpeed: HTTP ${imgRes.status}`);
    const imageData = Buffer.from(await imgRes.arrayBuffer());

    await mkdir(STICKER_RESULTS_DIR, { recursive: true });
    const filename = `${player.id}_result_${Date.now()}.png`;
    const filePath = path.join(STICKER_RESULTS_DIR, filename);
    await writeFile(filePath, imageData);
    const imageUrl = `/uploads/players/sticker-results/${filename}`;

    const saved = await prisma.playerStickerResult.create({
      data: {
        playerId: player.id,
        imageUrl,
        prompt: prompt.trim(),
        model: "gpt-image-2",
        size: "1024x1024",
        costUsd: 0.07,
        generationTimeSeconds: Math.round(elapsed * 10) / 10,
      },
    });

    console.log(`[sticker-queue-worker] generation done in ${elapsed.toFixed(1)}s — result ${saved.id}`);

    // ── 8. Split + background removal ──────────────────────────────────
    const metadata = await sharp(filePath).metadata();
    const imgW = metadata.width ?? 1024;
    const imgH = metadata.height ?? 1024;
    const quadW = Math.floor(imgW / 2);
    const quadH = Math.floor(imgH / 2);

    const outputDir = path.join(PACKS_DIR, player.id);
    const ts = Date.now();
    const packSubDir = path.join(outputDir, String(ts));
    await mkdir(packSubDir, { recursive: true });

    const fastapiUrl = (process.env["FASTAPI_URL"] ?? "http://localhost:8000").replace(/\/$/, "");
    const stickerUrls: Record<string, string> = {};

    for (const q of QUADRANTS) {
      const cropLeft = q.left === 0 ? 0 : quadW;
      const cropTop = q.top === 0 ? 0 : quadH;
      const cropped = await sharp(filePath)
        .extract({ left: cropLeft, top: cropTop, width: quadW, height: quadH })
        .png()
        .toBuffer();

      const base64 = cropped.toString("base64");
      const res = await fetch(`${fastapiUrl}/internal/remove-background`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ image_base64: base64, aggressiveness: "chroma", chroma_tolerance: 40, feather_radius: 1.5 }),
      });

      if (!res.ok) {
        const text = await res.text();
        throw new Error(`Background removal failed for sticker ${q.index}: ${text}`);
      }

      const processed = Buffer.from(await res.arrayBuffer());
      const webpBuffer = await sharp(processed)
        .trim()
        .resize(512, 512, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .webp({ quality: 90 })
        .toBuffer();

      const stickerFilename = `sticker_${q.index}.webp`;
      await writeFile(path.join(packSubDir, stickerFilename), webpBuffer);
      stickerUrls[`sticker${q.index}Url`] = `/uploads/players/sticker-packs/${player.id}/${ts}/${stickerFilename}?t=${ts}`;
    }

    // ── 9. Generate how-to card ─────────────────────────────────────────
    let howToCardUrl: string | null = null;
    try {
      const cardBuffer = await generateHowToCard();
      await writeFile(path.join(packSubDir, "how-to-use.png"), cardBuffer);
      howToCardUrl = `/uploads/players/sticker-packs/${player.id}/${ts}/how-to-use.png?t=${ts}`;
    } catch (cardErr) {
      console.warn("[sticker-queue-worker] how-to card generation failed (non-fatal):", cardErr);
    }

    // ── 10. Create the sticker pack record ─────────────────────────────
    const pack = await prisma.playerStickerPack.create({
      data: {
        playerId: player.id,
        resultId: saved.id,
        sticker1Url: stickerUrls["sticker1Url"],
        sticker2Url: stickerUrls["sticker2Url"],
        sticker3Url: stickerUrls["sticker3Url"],
        sticker4Url: stickerUrls["sticker4Url"],
        howToCardUrl,
      },
    });

    // ── 11. Mark job done ───────────────────────────────────────────────
    await prisma.stickerJobQueue.update({
      where: { id: job.id },
      data: { status: "done" },
    });

    console.log(`[sticker-queue-worker] job ${job.id} done — pack ${pack.id} created for player ${player.id} (${player.name})`);
    return json({ queued: "done", jobId: job.id, packId: pack.id, playerId: player.id });

  } catch (err) {
    const msg = (err as Error).message ?? String(err);
    console.error(`[sticker-queue-worker] job ${job.id} failed:`, msg);

    const currentJob = await prisma.stickerJobQueue.findUnique({ where: { id: job.id } });
    const attempts = currentJob?.attempts ?? job.attempts + 1;

    if (attempts < MAX_ATTEMPTS) {
      // Reset to pending for retry
      await prisma.stickerJobQueue.update({
        where: { id: job.id },
        data: { status: "pending", error: msg },
      });
      console.log(`[sticker-queue-worker] job ${job.id} will retry (attempt ${attempts}/${MAX_ATTEMPTS})`);
    } else {
      await prisma.stickerJobQueue.update({
        where: { id: job.id },
        data: { status: "failed", error: msg },
      });
      console.log(`[sticker-queue-worker] job ${job.id} permanently failed after ${attempts} attempts`);
    }

    return json({ queued: "error", jobId: job.id, error: msg });
  }
}

// Allow GET for health-check / status — returns queue counts
export async function GET(request: NextRequest) {
  if (!verifySecret(request)) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401 });
  }

  const [pending, processing, done, failed] = await Promise.all([
    prisma.stickerJobQueue.count({ where: { status: "pending" } }),
    prisma.stickerJobQueue.count({ where: { status: "processing" } }),
    prisma.stickerJobQueue.count({ where: { status: "done" } }),
    prisma.stickerJobQueue.count({ where: { status: "failed" } }),
  ]);

  return json({ pending, processing, done, failed });
}
