import express from "express";
import { createServer } from "http";
import { createServer as createHttpsServer } from "https";
import fs from "fs";
import os from "os";
import next from "next";
import path from "path";
import { Server as SocketIOServer } from "socket.io";
import { handleMcpRequest } from "./mcp-handler";

const dev = process.env.NODE_ENV !== "production";
const hostname = "0.0.0.0";
const port = parseInt(process.env.PORT || "3000", 10);

const app = next({ dev, hostname, port });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  const expressApp = express();
  
  // Create HTTP or HTTPS server based on environment
  let server;
  const isHttps = process.env.HTTPS === 'true';
  
  if (isHttps && process.env.SSL_CRT_FILE && process.env.SSL_KEY_FILE) {
    try {
      const cert = fs.readFileSync(process.env.SSL_CRT_FILE);
      const key = fs.readFileSync(process.env.SSL_KEY_FILE);
      server = createHttpsServer({ cert, key }, expressApp);
      console.log('🔐 HTTPS server enabled');
    } catch (error) {
      console.error('❌ Failed to load SSL certificates, falling back to HTTP:', error);
      server = createServer(expressApp);
    }
  } else {
    server = createServer(expressApp);
  }

  const io = new SocketIOServer(server, {
    cors: {
      origin: "*",
      methods: ["GET", "POST"],
    },
    transports: ["websocket"],
    pingTimeout: 60000,
  });

  // Make io available to API routes via global
  (globalThis as Record<string, unknown>).__socketIO = io;

  io.on("connection", (socket) => {
    console.log(`[Socket.io] Client connected: ${socket.id}`);

    socket.on("join:venue", (venueId: string) => {
      socket.join(`venue:${venueId}`);
      console.log(`[Socket.io] ${socket.id} joined venue:${venueId}`);
    });

    socket.on("join:player", (playerId: string) => {
      socket.join(`player:${playerId}`);
    });

    socket.on("leave:venue", (venueId: string) => {
      socket.leave(`venue:${venueId}`);
    });

    socket.on("disconnect", () => {
      console.log(`[Socket.io] Client disconnected: ${socket.id}`);
    });
  });

  // Serve cached face thumbnails from disk (generated by API route or backfill).
  // Legacy /uploads/players/thumbs/* URLs — redirect to the Next.js API handler.
  expressApp.get("/uploads/players/thumbs/:playerId", (req, res) => {
    const rawId = req.params.playerId;
    const playerId = rawId.endsWith(".webp") ? rawId.slice(0, -5) : rawId;
    res.redirect(302, `/api/uploads/players/thumbs/${playerId}`);
  });

  expressApp.use("/uploads", express.static(path.join(process.cwd(), "uploads")));

  // Serve public/ assets before Next.js so CourtPass host rewrites cannot
  // rewrite /images/*, /manifest.json, /sw.js, etc. to /book/images/* (404).
  expressApp.use(express.static(path.join(process.cwd(), "public")));

  // In dev, proxy /uploads to production when the file doesn't exist locally
  if (dev) {
    const productionBase = (process.env.APP_URL ?? "").replace(/\/$/, "");
    if (productionBase) {
      expressApp.use("/uploads", async (req, res) => {
        const remoteUrl = `${productionBase}/uploads${req.path}`;
        try {
          const upstream = await fetch(remoteUrl);
          if (!upstream.ok) { res.status(upstream.status).end(); return; }
          const contentType = upstream.headers.get("content-type") ?? "application/octet-stream";
          res.setHeader("Content-Type", contentType);
          const buf = Buffer.from(await upstream.arrayBuffer());
          res.send(buf);
        } catch {
          res.status(502).end();
        }
      });
    }
  }

  // MCP server — internal only, bearer-token protected (MCP_SERVER_SECRET).
  // Mounted before the Next.js catch-all so it is handled by Express directly.
  expressApp.post("/mcp", (req, res) => {
    handleMcpRequest(req, res).catch((err: unknown) => {
      console.error("[MCP] Unhandled error:", err);
      if (!res.headersSent) {
        res.writeHead(500, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "Internal server error" }));
      }
    });
  });

  expressApp.all("/{*path}", (req, res) => {
    return handle(req, res);
  });

  server.listen(port, hostname, () => {
    const protocol = process.env.HTTPS === "true" ? "https" : "http";
    const lanUrls = Object.values(os.networkInterfaces())
      .flat()
      .filter((a): a is NonNullable<typeof a> => {
        if (!a || a.internal) return false;
        const fam = a.family as string | number;
        return fam === "IPv4" || fam === 4;
      })
      .map((a) => `${protocol}://${a.address}:${port}`);

    console.log(`\n  CourtFlow listening on ${hostname}:${port} (${protocol.toUpperCase()})`);
    if (protocol === "http" && lanUrls.length > 0) {
      console.log(`  On your phone (same Wi‑Fi), open:`);
      for (const u of lanUrls) console.log(`    ${u}`);
      console.log(`  (Use http:// not https:// unless you started npm run dev:https)`);
    }
    console.log(`  Socket.io ready`);
    console.log(`  Mode: ${dev ? "development" : "production"}\n`);

    // ── Inline cron scheduler (replaces the dedicated expire-holds-cron service) ──
    // Only runs in production to avoid duplicate jobs during local dev.
    if (!dev) {
      const cronSecret = process.env.CRON_SECRET ?? "";
      const cronHeaders: Record<string, string> = cronSecret
        ? { Authorization: `Bearer ${cronSecret}` }
        : {};
      const localBase = `http://127.0.0.1:${port}`;

      async function cronCall(name: string, path: string) {
        const start = Date.now();
        try {
          const res = await fetch(`${localBase}${path}`, {
            method: "GET",
            headers: cronHeaders,
          });
          const body = await res.json().catch(() => ({}));
          console.log(
            `[cron] ${new Date().toISOString()} job=${name} status=${res.status} elapsed=${Date.now() - start}ms data=${JSON.stringify(body)}`
          );
        } catch (err) {
          console.error(
            `[cron] ${new Date().toISOString()} job=${name} ERROR: ${(err as Error).message}`
          );
        }
      }

      function cronTick() {
        const now = new Date();
        const mod = now.getHours() * 60 + now.getMinutes();
        const dow = now.getDay();

        cronCall("expire-holds", "/api/cron/expire-holds");

        if (now.getMinutes() === 0) {
          cronCall("auto-close-sessions", "/api/cron/auto-close-sessions");
        }
        if (mod === 2 * 60) {
          cronCall("open-bill-aging", "/api/cron/open-bill-aging");
        }
        if (dow === 1 && mod === 1) {
          cronCall("generate-invoices", "/api/cron/generate-invoices");
        }
      }

      const msUntilNextMinute =
        (60 - new Date().getSeconds()) * 1000 - new Date().getMilliseconds();
      setTimeout(() => {
        cronTick();
        setInterval(cronTick, 60_000);
      }, msUntilNextMinute);

      console.log("  Inline cron scheduler started (expire-holds every 1m, auto-close every 1h, aging daily 02:00, invoices Mon 00:01)");
    }
  });
});
