/* Strings mirror PWA `src/i18n/locales/tv/en.json` / `vi.json` (tablet.checkInScanner) plus a few RN-only keys. */
import type { TabletKioskLocale } from "./tablet-kiosk-locale";

export type CheckInScannerStringKey = keyof typeof CHECK_IN_SCANNER_EN;

const CHECK_IN_SCANNER_EN = {
  "welcomeTitle": "Welcome!",
  "tapToCheckIn": "Tap below to check in",
  "checkIn": "Check In",
  "checkInWithPhone": "Check in with phone",
  "faceHint": "The camera will scan your face to check you in.",
  "noMatchYet": "No match yet — adjust if needed",
  "positionFace": "Position your face — scanning starts in a moment",
  "holdStill": "Hold still — scanning now",
  "nextScanIn": "Next scan in",
  "scanning": "Scanning...",
  "retryAuto": "We'll try again automatically",
  "cameraReady": "Camera ready",
  "noFaceDetected": "No face detected",
  "somethingWrong": "Something went wrong",
  "lookAtCamera": "Look at the camera and try again",
  "tryAgain": "Please try again",
  "faceNotRecognized": "Face not recognised",
  "faceNotRecognizedHint": "Try checking in with your phone number, or scan again",
  "scanAgain": "Scan Again",
  "networkShowingLast": "Network issue — showing last check-in",
  "offlineSync": "Offline — will sync when network returns",
  "networkIssue": "Network issue",
  "seeStaff": "See staff for check-in",
  "checkInByPhone": "Check in by phone",
  "enterPhonePrompt": "Enter your phone number",
  "enterPhone": "Enter a phone number",
  "phonePlaceholder": "Phone number",
  "lookUp": "Look up",
  "phoneLabel": "Phone:",
  "levelLabel": "Level:",
  "alreadyCheckedIn": "Already checked in",
  "confirmCheckIn": "Confirm check-in",
  "homeCheckIn": "Registered player",
  "homeCheckInSub": "I've played here before",
  "homeFirstTime": "First Time?",
  "homeFirstTimeSub": "Register & pay to play",
  "regTitle": "Let's set up your account",
  "regFaceHint": "First, look at the camera",
  "regGotPhoto": "Got your photo!",
  "regLooksGood": "Looks good",
  "regRetake": "Retake",
  "registerPhotoTryAgain": "Try again",
  "registerPhotoAskStaff": "Please ask staff for help.",
  "regName": "Name (same as Reclub)",
  "regNamePlaceholder": "Your Reclub's name",
  "regPhone": "Phone number",
  "regPhonePlaceholder": "Your phone number",
  "regGender": "Gender",
  "regMale": "Male",
  "regFemale": "Female",
  "regLevel": "Level",
  "regBeginner": "Beginner",
  "regBeginnerDesc": "New to pickleball",
  "regIntermediate": "Intermediate",
  "regIntermediateDesc": "Know the rules, can rally",
  "regAdvanced": "Advanced",
  "regAdvancedDesc": "Competitive play",
  "regExistingUserTitle": "Existing user",
  "regExistingUserHint": "This face is already registered. Please use Registered player.",
  "regNext": "Next",
  "regPhoneRequiredAlertTitle": "Phone number needed",
  "regPhoneRequiredAlertMessage":
    "Your phone number is required so we can find your account. No Spam. No Ads.",
  "regPhoneRequiredOk": "Got it",
  "regPhoneRequiredDismissScrim": "Close",
  "payTitle": "Almost there, {{name}}!",
  "payReturningTitle": "Payment",
  "payScanQR": "Scan with your banking app then show staff to confirm",
  "payPartyPerson": "person",
  "payPartyPeople": "people",
  "payPartyMaxPeople": "Max 4 people",
  "paymentGroupOf": "Group of {{count}}",
  "payOr": "or",
  "payByCash": "Pay by cash",
  "payCashHint": "Tell staff you're paying cash",
  "payCashTitle": "Please pay {{amount}} cash to staff to complete check-in",
  "payWaitingForStaff": "Waiting for staff to confirm",
  "payTimeout": "Payment not confirmed",
  "payTimeoutHint": "Please show your payment to staff",
  "payCancelled": "Payment was not confirmed",
  "payCancelledHint": "Please see staff at the desk",
  "payNetworkError": "Connection issue",
  "payNetworkErrorHint": "Please see staff",
  "noActiveSession": "No session running right now",
  "noActiveSessionHint": "Please see staff",
  "regAlreadyRegistered": "You're already registered! Use Registered player instead.",
  "regPhoneExists": "This phone number is already registered. Use Registered player instead.",
  "successWelcomeBack": "Welcome back, {{name}}!",
  "successWelcomeNew": "Welcome to {{venue}}, {{name}}!",
  "successFaceRegistered": "Your face is registered — next time just scan to check in",
  "successHeadToTv": "When you're ready to play scan your face at the TV screen",
  "enterWristband": "Enter wristband number",
  "wristbandPlaceholder": "Wristband #",
  "wristbandLookUp": "Look up",
  "returningToMenu": "Returning to menu in {{seconds}}s…",
  "done": "Done",
  "cancel": "Cancel",
  "back": "Back",
  "backToHome": "Back to Home",
  "cameraPermissionTitle": "Camera access",
  "cameraPermissionHint": "Allow the camera to take your registration photo.",
  "allowCameraCta": "Allow Camera",
  "cameraStarting": "Starting camera…",
  "checkInComplete": "Check-in complete.",
  "registrationComplete": "Registration complete.",
  "cashPaymentConfirmed": "Cash payment confirmed.",
  "paymentConfirmed": "Payment confirmed.",
  "usePhoneInstead": "Use phone number instead",
  "tryAgainGeneric": "Try again",
  "registerAndContinue": "Register & Continue",
  "yourDetails": "Your details",
  "fullNamePlaceholder": "Full name",
  "scanToPay": "Scan to Pay",
  "waitingForPayment": "Waiting for payment…",
  "welcomeExclaim": "Welcome!",
  "kioskTagline": "More gameplay, more fun",
  "loginStaffLogin": "Staff Login",
  "loginPhonePlaceholder": "Phone number",
  "loginPasswordPlaceholder": "Password",
  "loginSignIn": "Sign In",
  "loginViewOnboarding": "View onboarding",
  "loginError": "Error",
  "loginErrorDetail": "Please enter phone and password",
  "loginFailed": "Login Failed",
  "onboardingSkip": "Skip",
  "onboardingNext": "Next",
  "onboardingGetStarted": "Get Started",
  "onboardingSlide1Title": "Seamless Payments",
  "onboardingSlide1Body":
    "Accept VietQR and cash payments for session check-ins with automatic confirmation.",
  "onboardingSlide2Title": "Fast Check-in",
  "onboardingSlide2Body":
    "Use face recognition or phone lookup to check players in within seconds.",
  "onboardingSlide3Title": "Session Management",
  "onboardingSlide3Body":
    "Open and close sessions, track revenue, and manage your venue from one place.",
  "subOfferWelcomeBack": "Welcome back, {{name}}!",
  "subOfferWelcomeNew": "Welcome to the club, {{name}}!",
  "subOfferSubtitleReturning": "Save with a package today?",
  "subOfferSubtitleNew": "Want to save with a package?",
  "subOfferSessions": "sessions",
  "subOfferDays": "days",
  "subOfferUnlimited": "Unlimited",
  "subOfferContinue": "Continue",
  "subOfferSkip": "Skip — pay today only",
  "subOfferChoosePackage": "Choose package (optional)",
  "subOfferBestChoice": "Best Choice",
  "subOfferSave": "Save {{pct}}%",
  "subOfferPayTodayTitle": "Pay for Today Only",
  "subOfferPayTodayDesc": "Single session — no package required",
  "subOfferOr": "OR",
  "exhaustedWelcomeBack": "Welcome back, {{name}}!",
  "exhaustedSubtitle": "You are in — consider buying a new package for next time.",
  "exhaustedSessionsLeft": "Sessions Left",
  "exhaustedDaysLeft": "Days Left",
  "exhaustedCountdown": "Returning to menu in {{seconds}}s…",
  "exhaustedShowPackages": "Show New Packages",
  "exhaustedNextTime": "Next time",
  "confirmedHeadline": "{{name}}, you are confirmed!",
  "confirmedHeadlineNoName": "You are confirmed!",
  "confirmedHaveFun": "Have fun games!",
  "confirmedSessionsRemaining": "Sessions\nRemaining",
  "confirmedDaysLeft": "Days\nLeft",
  "alreadyPaidWithName": "{{name}} already paid",
  "alreadyPaidNoName": "Already paid",
  "alreadyPaidPending": "Payment is pending confirmation — no new payment needed.",
  "alreadyPaidConfirmed": "This player has already paid for this session.",
  "existingPlayerNoName": "Existing player",
  "cashOverlayTitle": "Cash Payment",
  "cashOverlayHint": "Please hand the cash to the staff.\nWaiting for staff to confirm…",
  "cashOverlayCancel": "Cancel — go back",
  "phoneNotFound": "No player found with this phone number",
  "checkInConfirmedMsg": "Check-in confirmed.",
  "paymentConfirmedMsg": "Payment confirmed.",
  "alreadyCheckedInMsg": "{{name}} is already checked in for this session.",
  "cameraNotReady": "Camera not ready — try again.",
  "faceAlreadyExists": "{{name}} already exists. Use Registered player.",
  "courtpayTagline": "CourtPay",

  // ── Staff app general ──────────────────────────────────────────────────────
  "staffDashboard": "Staff Dashboard",
  "staffSelectVenue": "Select Venue",
  "staffProfile": "Profile",
  "staffPaymentSettings": "Payment Settings",
  "staffSessionDetails": "Session Details",
  "staffTabSession": "Session",
  "staffTabCheckIn": "Check-in",
  "staffTabPayment": "Payment",

  // ── Profile screen ─────────────────────────────────────────────────────────
  "profileName": "Name",
  "profilePhone": "Phone",
  "profilePushNotifications": "Push Notifications",
  "profilePaymentAlerts": "Payment alerts",
  "profilePaymentAlertsSub": "Receive push notifications when a payment is pending or confirmed, even when the app is in the background.",
  "profilePaymentSettings": "Payment Settings",
  "profileSubscriptions": "Subscriptions",
  "profileStaffDashboard": "Staff Dashboard",
  "profileBossDashboard": "Boss Dashboard",
  "profileAppearance": "Appearance",
  "profileAppearanceDark": "Dark",
  "profileAppearanceLight": "Light",
  "profileSessionHistory": "Session History",
  "profileSessionHistoryDesc": "View past sessions",
  "profileLogOut": "Log Out",
  "profileLogOutConfirm": "Are you sure you want to log out?",
  "profileGoToRole": "Go to Role / Tablet",
  "profilePinTitle": "Enter PIN",
  "profilePinSubtitle": "Enter the 4-digit boss PIN to access this menu",
  "profilePinIncorrect": "Incorrect PIN. Try again.",
  "profileLanguage": "Language",
  "profileReclubClub": "Reclub club",
  "profileReclubClubHint": "Default for session roster (all venues)",
  "profileReclubNotSet": "Not set",
  "profileReclubChooseTitle": "Choose Reclub club",

  // ── Session tab ────────────────────────────────────────────────────────────
  "sessionOpen": "Session Open",
  "sessionNoActive": "No Active Session",
  "sessionFee": "Fee",
  "sessionStarted": "Started",
  "sessionOpenBtn": "Open Session",
  "sessionCloseBtn": "Close Session",
  "sessionCloseConfirmTitle": "Close Session",
  "sessionCloseConfirmMsg": "Close the current session?",
  "sessionTodaySessions": "Today's Sessions",
  "sessionToday": "Today",
  "sessionClosed": "closed",
  "sessionRevenue": "Revenue",
  "sessionPayments": "payments",

  // ── Check-in tab ───────────────────────────────────────────────────────────
  "checkInNewPlayer": "New Player",
  "checkInExistingPlayer": "Existing Player",
  "checkInFaceCheckIn": "Face Check-in",
  "checkInStartCamera": "Start Camera",
  "checkInCapture": "Capture",
  "checkInOrPhoneFallback": "or phone fallback",
  "checkInLookupByPhone": "Lookup by phone",
  "checkInRegisterNewFace": "Register New Player Face",
  "checkInRegisterFaceHint": "Required for first registration.",
  "checkInPhotoQuality": "Photo quality (AWS Rekognition)",
  "checkInAnalyzingPhoto": "Analyzing photo quality...",
  "checkInFaceDetected": "Face detected",
  "checkInFaceSize": "Face size",
  "checkInLighting": "Lighting",
  "checkInFocus": "Focus",
  "checkInPlayerName": "Player name",
  "checkInRegisterBtn": "Register & Check-in",
  "checkInNoFaceBtn": "No face check-in",
  "checkInNoFaceTitle": "No face check-in",
  "checkInNoFaceHint": "For players who refuse face scanning",
  "checkInNoFaceStepName": "Step 1 · Name",
  "checkInNoFaceStepGender": "Step 2 · Gender",
  "checkInNoFaceStepLevel": "Step 3 · Level",
  "checkInNoFaceNext": "Next",
  "checkInNoFaceBack": "Back",
  "checkInNoFaceProceed": "Proceed to payment",
  "checkInNoFaceNameRequired": "Player name is required",
  "checkInNextCheckIn": "Next Check-in",
  "checkInSomethingWrong": "Something went wrong",
  "checkInStartOver": "Start Over",
  "checkInAwaitingPayment": "Awaiting Payment",
  "checkInConfirmCash": "Confirm Cash Payment",
  "checkInFaceNotRecognized": "Face not recognized. Use New Player flow.",
  "checkInNoFaceDetected": "No clear face detected. Retake and keep one face centered.",
  "checkInCaptureHintActive": "Use Capture to check this face. Switch camera if needed.",
  "checkInCaptureHintIdle": "Tap Start Camera to begin a manual face check-in.",

  // ── Payment tab ────────────────────────────────────────────────────────────
  "paymentSessionPaid": "Session (paid)",
  "paymentPlayers": "players",
  "paymentPending": "Pending",
  "paymentPaid": "Paid",
  "paymentNoPending": "No pending payments.",
  "paymentNoPaid": "No paid check-ins this session.",
  "paymentSkill": "Skill",
  "paymentRegistration": "Registration",
  "paymentCheckIn": "Check-in",
  "paymentWaiting": "Waiting",
  "paymentConfirm": "Confirm",
  "paymentCancel": "Cancel",
  "paymentCancelTitle": "Cancel Payment",
  "paymentCancelMsg": "Cancel this pending payment?",
  "paymentCancelPaidTitle": "Cancel payment?",
  "paymentRefunded": "Refunded",
  "paymentMistake": "Mistake",
  "paymentFreePass": "Free Pass",
  "paymentGoBack": "Go back",
  "paymentSubLeft": "Subscription left",
  "paymentUnlimited": "Unlimited",
  "paymentDays": "days",
  "paymentSessions": "sessions",
  "paymentGroup": "Group",
  "paymentWhichGroup": "Which Group?",
  "paymentGroupNone": "No group payer",
  "paymentGroupNoneHint": "Clear 'Paid by' from this card",
  "paymentPaidBy": "Paid by {{name}}",

  // ── Payment settings ───────────────────────────────────────────────────────
  "paySettingsTitle": "Payment Settings",
  "paySettingsSave": "Save",
  "paySettingsSaving": "Saving...",
  "paySettingsSaved": "Saved ✓",
  "paySettingsSessionFee": "Session Fee (VND)",
  "paySettingsVietQR": "VietQR",
  "paySettingsQRPreview": "QR Preview",
  "paySettingsBank": "Bank",
  "paySettingsSelectBank": "Select bank",
  "paySettingsAccountNumber": "Account Number",
  "paySettingsAccountHolder": "Account Holder",
  "paySettingsAccountPlaceholder": "Account #",
  "paySettingsAccountNamePlaceholder": "Account name",
  "paySettingsAutoApproval": "Automatic payment approval",
  "paySettingsPhone": "Phone",
  "paySettingsSearchBank": "Search by name or BIN…",
  "paySettingsNotificationSound": "Notification Sound",
  "paySettingsNotificationSoundHint": "Sound when a payment arrives or is confirmed.",
  "paySettingsSelectSound": "Select sound",
  "paySettingsClose": "Close",
  "paySettingsVenueSelect": "Select Venue",

  // ── Player Discounts ────────────────────────────────────────────────────────
  "playerDiscountTitle": "Player discounts",
  "playerDiscountEmpty": "No discounts set",
  "playerDiscountAdd": "Add discount",
  "playerDiscountDeleteConfirm": "Delete discount for this player?",
  "playerDiscountEditTitle": "Edit discount",
  "playerDiscountCreateTitle": "Create discount",
  "playerDiscountSearchPlaceholder": "Search player by name or phone...",
  "playerDiscountNoResults": "No players found",
  "playerDiscountChange": "Change",
  "playerDiscountFixed": "Fixed price",
  "playerDiscountPercent": "Percentage",
  "playerDiscountCustomFeeLabel": "Custom price (VND)",
  "playerDiscountDefaultFee": "Default: {{fee}} VND",
  "playerDiscountPctLabel": "Discount %",
  "playerDiscountPctResult": "Player pays: {{price}} VND",
  "playerDiscountNoteLabel": "Note (optional)",
  "playerDiscountNotePlaceholder": "e.g. Coach, Regular, Friend...",
  "playerDiscountSave": "Save",
  "playerDiscountSaveError": "Could not save discount",
  "playerDiscountDelete": "Delete",
  "playerDiscountCancel": "Cancel",

  // ── Reclub KPIs ─────────────────────────────────────────────────────────────
  "reclubKpiMatched": "Matched",
  "reclubKpiAbsent": "Absent",
  "reclubKpiWalkIn": "Walk-in",
  "reclubKpiBooked": "Booked",
  "reclubKpiPaid": "Paid",
  "reclubKpiUnmatched": "Unmatched",
  "reclubKpiExpected": "Expected",

  // ── Reclub Roster / Session Detail ──────────────────────────────────────────
  "reclubFetchRoster": "Load Reclub List",
  "reclubNoEvents": "No Reclub event today. CourtPay session running normally.",
  "reclubLegendTitle": "Legend",
  "reclubLegendMatchedPaid": "Matched & paid",
  "reclubLegendAbsent": "Absent",
  "reclubLegendWalkIn": "Walk-in",
  "reclubTabPayments": "Payments",
  "reclubTabReclub": "Reclub",
  "reclubNoSnapshot": "No Reclub data for this session.",
  "reclubNoSnapshotHint": "A snapshot is created when a session with a Reclub roster is closed.",

  // ── Boss Dashboard ─────────────────────────────────────────────────────────
  "bossDashboardTitle": "Boss Dashboard",
  "bossDashboardTabToday": "Today",
  "bossDashboardTabHistory": "History",
  "bossDashboardTabSubs": "Subs",
  "bossDashboardTabPlayers": "Players",
  "bossDashboardTabBilling": "Billing",
  "bossDashboardSessionPayments": "Number of payments",
  "bossDashboardRevenue": "Revenue",
  "bossDashboardSubscribers": "Subscribers",
  "bossDashboardPending": "Pending",
  "bossDashboardTodaySessions": "Today's sessions",
  "bossDashboardNoSessions": "No sessions today.",
  "bossDashboardRevenueSummary": "Revenue summary",
  "bossDashboardToday": "Today",
  "bossDashboardYesterday": "Yesterday",
  "bossDashboardThisWeek": "This week",
  "bossDashboardThisMonth": "This month",
  "bossDashboardAllTime": "All time",
  "bossDashboardPayments": "payments",
  "bossDashboardDailyRevenue": "Daily revenue (all today's payments)",
  "bossDashboardPastSessions": "Past sessions",
  "bossDashboardSessionPlayersPaid": "players",
  "bossDashboardNoPastSessions": "No past sessions.",
  "bossDashboardTotalPlayers": "Total players",
  "bossDashboardNewThisWeek": "New this week",
  "bossDashboardWithSubscription": "With subscription",
  "bossDashboardAvgReturn": "Avg return (days)",
  "bossDashboardAvgVisits": "Avg visits / player",
  "bossDashboardReturned": "Returned (15d) %",
  "bossDashboardNoPlayers": "No players found.",
  "bossDashboardLastSeen": "Last seen",
  "bossDashboardAvgReturnDays": "avg return d",
  "bossDashboardAll": "All",
  "bossDashboardMale": "Male",
  "bossDashboardFemale": "Female",
  "bossDashboardSearchPlaceholder": "Search by name or phone…",
  "bossDashboardBillingThisWeek": "This week",
  "bossDashboardBillingPayments": "Payments",
  "bossDashboardBillingBase": "Base",
  "bossDashboardBillingSubPayments": "Subscription payments",
  "bossDashboardBillingSubAddon": "Add-on",
  "bossDashboardBillingAutoPayment": "Auto-payment confirmed",
  "bossDashboardBillingEstimated": "Estimated total",
  "bossDashboardBillingTapView": "Tap card to view weekly payments.",
  "bossDashboardBillingPastWeeks": "Past weeks",
  "bossDashboardBillingNoBilling": "No billing data yet",
  "bossDashboardBillingWeekPaid": "✓ Week paid",
  "bossDashboardBillingOverdue": "Invoice overdue ⚠️",
  "bossDashboardBillingDue": "Invoice due ⏳",
  "bossDashboardBillingTotalPayments": "Total payments",
  "bossDashboardBillingBaseCharges": "Base charges",
  "bossDashboardBillingSubAddonLabel": "Subscription add-on",
  "bossDashboardBillingAutoPayAddon": "Auto-Payment add-on",
  "bossDashboardBillingTotal": "Total",
  "bossDashboardBillingPaid": "Paid",
  "bossDashboardBillingTapCollapse": "Tap to collapse",
  "bossDashboardBillingTapDetails": "✓ Tap for details",
  "bossDashboardBillingPayNow": "Pay now — scan QR ▼",
  "bossDashboardBillingHideQR": "Hide QR ▲",
  "bossDashboardBillingAmount": "Amount",
  "bossDashboardBillingRef": "Ref",
  "bossDashboardBillingAutoConfirm": "Payment confirmed automatically once received",
  "bossDashboardBillingWaiting": "Waiting for payment...",
  "bossDashboardBillingPaymentReceived": "Payment received — thank you!",
  "bossDashboardBillingNoQR": "Could not generate QR code",
  "bossDashboardClosed": "closed",
  "bossExportRevenueTitle": "Export revenue (CSV)",
  "bossExportFrom": "From",
  "bossExportTo": "To",
  "bossExportButton": "Export",
  "bossExportCancel": "Cancel",
  "bossExportPreparing": "Preparing export…",
  "bossExportNoData": "No sessions in this date range.",
  "bossExportInvalidRange": "From date must be before or equal to To date.",
  "sessionDetailExportCsv": "Export session CSV",

  // ── Staff Dashboard ────────────────────────────────────────────────────────
  "staffDashboardTitle": "Staff Dashboard",
  "staffDashboardTabSubscribers": "Subscribers",
  "staffDashboardTabPlayers": "Players",
  "staffDashboardTotalPlayers": "Total players",
  "staffDashboardNewThisWeek": "New this week",
  "staffDashboardWithSub": "With subscription",
  "staffDashboardAvgVisits": "Avg visits / player",
  "staffDashboardNoPlayers": "No players found.",
  "staffDashboardLastSeen": "Last seen",
  "staffDashboardVisits": "visits",
  "staffDashboardShareTitle": "Share balance check link",
  "staffDashboardShareDesc": "Players can check their session balance without installing the app.",
  "staffDashboardShareBtn": "Share link & QR",
  "staffDashboardShareModalTitle": "Share balance check",
  "staffDashboardShareModalDesc": "Send this link to your players so they can check their session balance anytime — no app needed.",
  "staffDashboardShareModalClose": "Close",
  "staffDashboardShareModalShare": "Share link & QR",

  // ── Subscriptions screen ────────────────────────────────────────────────────
  "subsTitle": "Subscriptions",
  "subsTabPackages": "Packages",
  "subsTabSubscribers": "Subscribers",
  "subsShowInFlow": "Show in CourtPay check-in",
  "subsShowInFlowDesc": "When off, players go directly to single-session payment and skip the packages screen.",
  "subsNoPackages": "No packages yet",
  "subsCreateForMe": "Create packages for me",
  "subsCreateCustom": "or create custom package",
  "subsAddPackage": "Add package",
  "subsMaxReached": "Maximum {{max}} active packages reached.",
  "subsBestChoice": "Best Choice",
  "subsSave": "Save {{pct}}%",
  "subsUnlimitedSessions": "Unlimited sessions",
  "subsSessions": "sessions",
  "subsActiveSubs": "Active subs",
  "subsDays": "days",
  "subsEdit": "Edit",
  "subsDelete": "Delete",
  "subsModalCreateTitle": "Create package",
  "subsModalEditTitle": "Edit package",
  "subsPackageName": "Package name",
  "subsPackageNamePlaceholder": "e.g. Monthly Pass",
  "subsSessionsIncluded": "Sessions included",
  "subsUnlimited": "Unlimited",
  "subsValidDays": "Valid for (days)",
  "subsPriceVND": "Price (VND)",
  "subsDiscountPct": "Discount (%)",
  "subsPerks": "Perks (optional)",
  "subsCancel": "Cancel",
  "subsSaveBtn": "Save",
  "subsShareTitle": "Share balance check link",
  "subsShareDesc": "Players can check their session balance without installing the app.",
  "subsShareBtn": "Share link & QR",
  "subsShareModalTitle": "Share balance check",
  "subsShareModalDesc": "Send this link to your players so they can check their session balance anytime — no app needed.",
  "subsShareModalClose": "Close",
  "subsShareModalShare": "Share",

  // ── Continue As (role select) screen ───────────────────────────────────────
  "continueAsTitle": "Continue as",
  "continueAsSubtitle": "Select your role to get started",
  "continueAsWelcome": "Welcome",
  "continueAsSignOut": "Sign out",
  "continueAsStaffLabel": "Staff Dashboard",
  "continueAsStaffDesc": "Manage sessions, check-ins, and payments",
  "continueAsAdminLabel": "Admin",
  "continueAsAdminDesc": "Full admin panel (web view)",
  "continueAsTabletLabel": "Tablet Mode",
  "continueAsTabletDesc": "Self check-in or CourtPay kiosk",
  "continueAsLogOutTitle": "Log Out",
  "continueAsLogOutMsg": "Are you sure?",
  "continueAsAccessRestricted": "Access restricted",
  "continueAsAccessRestrictedMsg": "Only admin accounts can access the Admin panel.",

  // ── Boss Subscription Detail ────────────────────────────────────────────────
  "bossSubDetailTitle": "Subscription Detail",
  "bossSubDetailPurchased": "Purchased",
  "bossSubDetailExpires": "Expires",
  "bossSubDetailLastCheckIn": "Last check-in",
  "bossSubDetailUsed": "used",
  "bossSubDetailCheckInHistory": "Check-in history",
  "bossSubDetailNoCheckIns": "No check-ins yet for this subscription.",
  "bossSubDetailRetry": "Retry",
  "bossSubDetailNotFound": "Subscription not found",
  "bossSubDetailUnlimited": "Unlimited"
} as const;

const CHECK_IN_SCANNER_VI = {
  "welcomeTitle": "Chào mừng!",
  "tapToCheckIn": "Nhấn bên dưới để check-in",
  "checkIn": "Điểm danh",
  "checkInWithPhone": "Điểm danh bằng số điện thoại",
  "faceHint": "Camera sẽ quét khuôn mặt để check-in cho bạn.",
  "noMatchYet": "Chưa nhận diện được — điều chỉnh lại nếu cần",
  "positionFace": "Đặt khuôn mặt vào khung — sẽ quét ngay",
  "holdStill": "Giữ yên — đang quét",
  "nextScanIn": "Lần quét tiếp theo sau",
  "scanning": "Đang quét...",
  "retryAuto": "Hệ thống sẽ tự quét lại",
  "cameraReady": "Camera sẵn sàng",
  "noFaceDetected": "Không phát hiện khuôn mặt",
  "somethingWrong": "Đã có lỗi xảy ra",
  "lookAtCamera": "Nhìn vào camera và thử lại",
  "tryAgain": "Vui lòng thử lại",
  "faceNotRecognized": "Không nhận diện được khuôn mặt",
  "faceNotRecognizedHint": "Hãy check-in bằng số điện thoại, hoặc quét lại",
  "scanAgain": "Quét lại",
  "networkShowingLast": "Lỗi mạng — đang hiển thị lần check-in gần nhất",
  "offlineSync": "Đang offline — sẽ đồng bộ khi có mạng",
  "networkIssue": "Lỗi mạng",
  "seeStaff": "Liên hệ nhân viên để check-in",
  "checkInByPhone": "Điểm danh bằng điện thoại",
  "enterPhonePrompt": "Nhập số điện thoại của bạn",
  "enterPhone": "Nhập số điện thoại",
  "phonePlaceholder": "Số điện thoại",
  "lookUp": "Tra cứu",
  "phoneLabel": "Điện thoại:",
  "levelLabel": "Trình độ:",
  "alreadyCheckedIn": "Đã check-in",
  "confirmCheckIn": "Xác nhận điểm danh",
  "homeCheckIn": "Người chơi đã đăng ký",
  "homeCheckInSub": "Tôi đã chơi ở đây trước",
  "homeFirstTime": "Lần đầu?",
  "homeFirstTimeSub": "Đăng ký & thanh toán",
  "regTitle": "Hãy thiết lập tài khoản của bạn",
  "regFaceHint": "Trước tiên, nhìn vào camera",
  "regGotPhoto": "Đã chụp ảnh!",
  "regLooksGood": "Được rồi",
  "regRetake": "Chụp lại",
  "registerPhotoTryAgain": "Thử lại",
  "registerPhotoAskStaff": "Vui lòng nhờ nhân viên hỗ trợ.",
  "regName": "Tên (giống Reclub)",
  "regNamePlaceholder": "Tên Reclub của bạn",
  "regPhone": "Số điện thoại",
  "regPhonePlaceholder": "Số điện thoại của bạn",
  "regGender": "Giới tính",
  "regMale": "Nam",
  "regFemale": "Nữ",
  "regLevel": "Trình độ",
  "regBeginner": "Mới chơi",
  "regBeginnerDesc": "Mới chơi pickleball",
  "regIntermediate": "Trung bình",
  "regIntermediateDesc": "Biết luật, đánh được",
  "regAdvanced": "Khá",
  "regAdvancedDesc": "Chơi thi đấu",
  "regExistingUserTitle": "Người dùng đã tồn tại",
  "regExistingUserHint": "Khuôn mặt này đã được đăng ký. Vui lòng chọn Người chơi đã đăng ký.",
  "regNext": "Tiếp",
  "regPhoneRequiredAlertTitle": "Cần số điện thoại",
  "regPhoneRequiredAlertMessage":
    "Chúng tôi cần số điện thoại của bạn để tìm tài khoản. Không spam. Không quảng cáo.",
  "regPhoneRequiredOk": "Đã hiểu",
  "regPhoneRequiredDismissScrim": "Đóng",
  "payTitle": "Sắp xong rồi, {{name}}!",
  "payReturningTitle": "Thanh toán",
  "payScanQR": "Quét bằng ứng dụng ngân hàng rồi cho nhân viên xác nhận",
  "payPartyPerson": "người",
  "payPartyPeople": "người",
  "payPartyMaxPeople": "Tối đa 4 người",
  "paymentGroupOf": "Nhóm {{count}} người",
  "payOr": "hoặc",
  "payByCash": "Trả tiền mặt",
  "payCashHint": "Báo nhân viên bạn trả tiền mặt",
  "payCashTitle": "Vui lòng trả {{amount}} tiền mặt cho nhân viên",
  "payWaitingForStaff": "Đang chờ nhân viên xác nhận",
  "payTimeout": "Chưa xác nhận thanh toán",
  "payTimeoutHint": "Vui lòng cho nhân viên xem thanh toán",
  "payCancelled": "Thanh toán chưa được xác nhận",
  "payCancelledHint": "Vui lòng gặp nhân viên",
  "payNetworkError": "Lỗi kết nối",
  "payNetworkErrorHint": "Vui lòng gặp nhân viên",
  "noActiveSession": "Hiện không có phiên nào",
  "noActiveSessionHint": "Vui lòng gặp nhân viên",
  "regAlreadyRegistered": "Bạn đã đăng ký rồi! Hãy chọn Người chơi đã đăng ký.",
  "regPhoneExists": "Số điện thoại này đã được đăng ký. Hãy chọn Người chơi đã đăng ký.",
  "successWelcomeBack": "Chào mừng trở lại, {{name}}!",
  "successWelcomeNew": "Chào mừng đến {{venue}}, {{name}}!",
  "successFaceRegistered": "Khuôn mặt đã được đăng ký — lần sau chỉ cần quét để check-in",
  "successHeadToTv": "Khi sẵn sàng chơi hãy quét khuôn mặt tại màn hình TV",
  "enterWristband": "Nhập số vòng tay",
  "wristbandPlaceholder": "Số vòng tay",
  "wristbandLookUp": "Tra cứu",
  "returningToMenu": "Quay lại menu sau {{seconds}} giây…",
  "done": "Xong",
  "cancel": "Hủy",
  "back": "Quay lại",
  "backToHome": "Về trang chủ",
  "cameraPermissionTitle": "Quyền truy cập camera",
  "cameraPermissionHint": "Cho phép camera để chụp ảnh đăng ký.",
  "allowCameraCta": "Cho phép camera",
  "cameraStarting": "Đang khởi động camera…",
  "checkInComplete": "Check-in hoàn tất.",
  "registrationComplete": "Đăng ký hoàn tất.",
  "cashPaymentConfirmed": "Đã xác nhận thanh toán tiền mặt.",
  "paymentConfirmed": "Đã xác nhận thanh toán.",
  "usePhoneInstead": "Dùng số điện thoại thay thế",
  "tryAgainGeneric": "Thử lại",
  "registerAndContinue": "Đăng ký & tiếp tục",
  "yourDetails": "Thông tin của bạn",
  "fullNamePlaceholder": "Họ và tên",
  "scanToPay": "Quét để thanh toán",
  "waitingForPayment": "Đang chờ thanh toán…",
  "welcomeExclaim": "Chào mừng!",
  "kioskTagline": "Nhiều trận hơn, nhiều niềm vui hơn",
  "loginStaffLogin": "Đăng nhập nhân viên",
  "loginPhonePlaceholder": "Số điện thoại",
  "loginPasswordPlaceholder": "Mật khẩu",
  "loginSignIn": "Đăng nhập",
  "loginViewOnboarding": "Xem hướng dẫn",
  "loginError": "Lỗi",
  "loginErrorDetail": "Vui lòng nhập số điện thoại và mật khẩu",
  "loginFailed": "Đăng nhập thất bại",
  "onboardingSkip": "Bỏ qua",
  "onboardingNext": "Tiếp",
  "onboardingGetStarted": "Bắt đầu",
  "onboardingSlide1Title": "Thanh toán liền mạch",
  "onboardingSlide1Body":
    "Nhận VietQR và tiền mặt cho check-in buổi chơi với xác nhận tự động.",
  "onboardingSlide2Title": "Check-in nhanh",
  "onboardingSlide2Body":
    "Dùng nhận diện khuôn mặt hoặc tra số điện thoại để điểm danh trong vài giây.",
  "onboardingSlide3Title": "Quản lý buổi chơi",
  "onboardingSlide3Body":
    "Mở và đóng buổi chơi, theo dõi doanh thu và quản lý địa điểm tại một nơi.",
  "subOfferWelcomeBack": "Chào mừng trở lại, {{name}}!",
  "subOfferWelcomeNew": "Chào mừng đến câu lạc bộ, {{name}}!",
  "subOfferSubtitleReturning": "Tiết kiệm với gói hôm nay?",
  "subOfferSubtitleNew": "Muốn tiết kiệm với gói chơi?",
  "subOfferSessions": "buổi",
  "subOfferDays": "ngày",
  "subOfferUnlimited": "Không giới hạn",
  "subOfferContinue": "Tiếp tục",
  "subOfferSkip": "Bỏ qua — chỉ trả hôm nay",
  "subOfferChoosePackage": "Chọn gói (tùy chọn)",
  "subOfferBestChoice": "Tốt nhất",
  "subOfferSave": "Tiết kiệm {{pct}}%",
  "subOfferPayTodayTitle": "Chỉ trả hôm nay",
  "subOfferPayTodayDesc": "Một buổi — không cần gói",
  "subOfferOr": "HOẶC",
  "exhaustedWelcomeBack": "Chào mừng trở lại, {{name}}!",
  "exhaustedSubtitle": "Bạn đã vào — hãy mua gói mới cho lần sau.",
  "exhaustedSessionsLeft": "Buổi còn lại",
  "exhaustedDaysLeft": "Ngày còn lại",
  "exhaustedCountdown": "Quay lại menu sau {{seconds}} giây…",
  "exhaustedShowPackages": "Xem gói mới",
  "exhaustedNextTime": "Lần sau",
  "confirmedHeadline": "{{name}}, bạn đã được xác nhận!",
  "confirmedHeadlineNoName": "Bạn đã được xác nhận!",
  "confirmedHaveFun": "Chúc bạn chơi vui vẻ!",
  "confirmedSessionsRemaining": "Buổi\ncòn lại",
  "confirmedDaysLeft": "Ngày\ncòn lại",
  "alreadyPaidWithName": "{{name}} đã thanh toán",
  "alreadyPaidNoName": "Đã thanh toán",
  "alreadyPaidPending": "Thanh toán đang chờ xác nhận — không cần thanh toán thêm.",
  "alreadyPaidConfirmed": "Người chơi này đã thanh toán cho buổi này.",
  "existingPlayerNoName": "Người chơi đã tồn tại",
  "cashOverlayTitle": "Thanh toán tiền mặt",
  "cashOverlayHint": "Vui lòng đưa tiền mặt cho nhân viên.\nĐang chờ nhân viên xác nhận…",
  "cashOverlayCancel": "Hủy — quay lại",
  "phoneNotFound": "Không tìm thấy người chơi với số điện thoại này",
  "checkInConfirmedMsg": "Điểm danh thành công.",
  "paymentConfirmedMsg": "Đã xác nhận thanh toán.",
  "alreadyCheckedInMsg": "{{name}} đã điểm danh cho buổi này.",
  "cameraNotReady": "Camera chưa sẵn sàng — thử lại.",
  "faceAlreadyExists": "{{name}} đã tồn tại. Chọn Người chơi đã đăng ký.",
  "courtpayTagline": "CourtPay",

  // ── Staff app general ──────────────────────────────────────────────────────
  "staffDashboard": "Bảng điều khiển nhân viên",
  "staffSelectVenue": "Chọn địa điểm",
  "staffProfile": "Hồ sơ",
  "staffPaymentSettings": "Cài đặt thanh toán",
  "staffSessionDetails": "Chi tiết buổi chơi",
  "staffTabSession": "Buổi chơi",
  "staffTabCheckIn": "Điểm danh",
  "staffTabPayment": "Thanh toán",

  // ── Profile screen ─────────────────────────────────────────────────────────
  "profileName": "Tên",
  "profilePhone": "Điện thoại",
  "profilePushNotifications": "Thông báo đẩy",
  "profilePaymentAlerts": "Cảnh báo thanh toán",
  "profilePaymentAlertsSub": "Nhận thông báo đẩy khi có thanh toán đang chờ hoặc đã xác nhận, ngay cả khi ứng dụng đang chạy nền.",
  "profilePaymentSettings": "Cài đặt thanh toán",
  "profileSubscriptions": "Gói đăng ký",
  "profileStaffDashboard": "Bảng điều khiển nhân viên",
  "profileBossDashboard": "Bảng điều khiển quản lý",
  "profileAppearance": "Giao diện",
  "profileAppearanceDark": "Tối",
  "profileAppearanceLight": "Sáng",
  "profileSessionHistory": "Lịch sử buổi chơi",
  "profileSessionHistoryDesc": "Xem các buổi trước",
  "profileLogOut": "Đăng xuất",
  "profileLogOutConfirm": "Bạn có chắc muốn đăng xuất?",
  "profileGoToRole": "Chuyển vai / Máy tính bảng",
  "profilePinTitle": "Nhập mã PIN",
  "profilePinSubtitle": "Nhập mã PIN 4 chữ số của quản lý để truy cập",
  "profilePinIncorrect": "Mã PIN sai. Thử lại.",
  "profileLanguage": "Ngôn ngữ",
  "profileReclubClub": "Câu lạc bộ Reclub",
  "profileReclubClubHint": "Mặc định cho danh sách buổi (mọi địa điểm)",
  "profileReclubNotSet": "Chưa chọn",
  "profileReclubChooseTitle": "Chọn câu lạc bộ Reclub",

  // ── Session tab ────────────────────────────────────────────────────────────
  "sessionOpen": "Buổi đang mở",
  "sessionNoActive": "Không có buổi nào",
  "sessionFee": "Phí",
  "sessionStarted": "Bắt đầu",
  "sessionOpenBtn": "Mở buổi chơi",
  "sessionCloseBtn": "Đóng buổi chơi",
  "sessionCloseConfirmTitle": "Đóng buổi chơi",
  "sessionCloseConfirmMsg": "Đóng buổi chơi hiện tại?",
  "sessionTodaySessions": "Buổi hôm nay",
  "sessionToday": "Hôm nay",
  "sessionClosed": "đã đóng",
  "sessionRevenue": "Doanh thu",
  "sessionPayments": "thanh toán",

  // ── Check-in tab ───────────────────────────────────────────────────────────
  "checkInNewPlayer": "Người chơi mới",
  "checkInExistingPlayer": "Người chơi cũ",
  "checkInFaceCheckIn": "Điểm danh khuôn mặt",
  "checkInStartCamera": "Mở camera",
  "checkInCapture": "Chụp",
  "checkInOrPhoneFallback": "hoặc dùng số điện thoại",
  "checkInLookupByPhone": "Tra cứu theo điện thoại",
  "checkInRegisterNewFace": "Đăng ký khuôn mặt người chơi mới",
  "checkInRegisterFaceHint": "Bắt buộc khi đăng ký lần đầu.",
  "checkInPhotoQuality": "Chất lượng ảnh (AWS Rekognition)",
  "checkInAnalyzingPhoto": "Đang phân tích chất lượng ảnh...",
  "checkInFaceDetected": "Phát hiện khuôn mặt",
  "checkInFaceSize": "Kích thước khuôn mặt",
  "checkInLighting": "Ánh sáng",
  "checkInFocus": "Tiêu cự",
  "checkInPlayerName": "Tên người chơi",
  "checkInRegisterBtn": "Đăng ký & Điểm danh",
  "checkInNoFaceBtn": "Điểm danh không khuôn mặt",
  "checkInNoFaceTitle": "Điểm danh không khuôn mặt",
  "checkInNoFaceHint": "Dành cho người chơi từ chối quét khuôn mặt",
  "checkInNoFaceStepName": "Bước 1 · Tên",
  "checkInNoFaceStepGender": "Bước 2 · Giới tính",
  "checkInNoFaceStepLevel": "Bước 3 · Trình độ",
  "checkInNoFaceNext": "Tiếp",
  "checkInNoFaceBack": "Quay lại",
  "checkInNoFaceProceed": "Tiếp tục thanh toán",
  "checkInNoFaceNameRequired": "Vui lòng nhập tên người chơi",
  "checkInNextCheckIn": "Điểm danh tiếp theo",
  "checkInSomethingWrong": "Đã có lỗi xảy ra",
  "checkInStartOver": "Bắt đầu lại",
  "checkInAwaitingPayment": "Đang chờ thanh toán",
  "checkInConfirmCash": "Xác nhận thanh toán tiền mặt",
  "checkInFaceNotRecognized": "Không nhận diện khuôn mặt. Dùng luồng Người chơi mới.",
  "checkInNoFaceDetected": "Không phát hiện khuôn mặt rõ ràng. Chụp lại với một khuôn mặt ở giữa.",
  "checkInCaptureHintActive": "Dùng Chụp để điểm danh khuôn mặt. Chuyển camera nếu cần.",
  "checkInCaptureHintIdle": "Nhấn Mở camera để bắt đầu điểm danh khuôn mặt thủ công.",

  // ── Payment tab ────────────────────────────────────────────────────────────
  "paymentSessionPaid": "Buổi (đã thanh toán)",
  "paymentPlayers": "người chơi",
  "paymentPending": "Chờ xác nhận",
  "paymentPaid": "Đã thanh toán",
  "paymentNoPending": "Không có thanh toán đang chờ.",
  "paymentNoPaid": "Chưa có điểm danh nào trong buổi này.",
  "paymentSkill": "Trình độ",
  "paymentRegistration": "Đăng ký",
  "paymentCheckIn": "Điểm danh",
  "paymentWaiting": "Đang chờ",
  "paymentConfirm": "Xác nhận",
  "paymentCancel": "Hủy",
  "paymentCancelTitle": "Hủy thanh toán",
  "paymentCancelMsg": "Hủy thanh toán đang chờ này?",
  "paymentCancelPaidTitle": "Hủy thanh toán?",
  "paymentRefunded": "Hoàn tiền",
  "paymentMistake": "Nhầm lẫn",
  "paymentFreePass": "Miễn phí",
  "paymentGoBack": "Quay lại",
  "paymentSubLeft": "Gói còn lại",
  "paymentUnlimited": "Không giới hạn",
  "paymentDays": "ngày",
  "paymentSessions": "buổi",
  "paymentGroup": "Nhóm",
  "paymentWhichGroup": "Nhóm nào?",
  "paymentGroupNone": "Không chọn người trả nhóm",
  "paymentGroupNoneHint": "Xoá 'Đã trả bởi' khỏi thẻ này",
  "paymentPaidBy": "Đã trả bởi {{name}}",

  // ── Payment settings ───────────────────────────────────────────────────────
  "paySettingsTitle": "Cài đặt thanh toán",
  "paySettingsSave": "Lưu",
  "paySettingsSaving": "Đang lưu...",
  "paySettingsSaved": "Đã lưu ✓",
  "paySettingsSessionFee": "Phí buổi chơi (VND)",
  "paySettingsVietQR": "VietQR",
  "paySettingsQRPreview": "Xem trước QR",
  "paySettingsBank": "Ngân hàng",
  "paySettingsSelectBank": "Chọn ngân hàng",
  "paySettingsAccountNumber": "Số tài khoản",
  "paySettingsAccountHolder": "Chủ tài khoản",
  "paySettingsAccountPlaceholder": "Số tài khoản",
  "paySettingsAccountNamePlaceholder": "Tên tài khoản",
  "paySettingsAutoApproval": "Tự động xác nhận thanh toán",
  "paySettingsPhone": "Điện thoại",
  "paySettingsSearchBank": "Tìm theo tên hoặc BIN…",
  "paySettingsNotificationSound": "Âm thanh thông báo",
  "paySettingsNotificationSoundHint": "Âm thanh khi có thanh toán mới hoặc đã xác nhận.",
  "paySettingsSelectSound": "Chọn âm thanh",
  "paySettingsClose": "Đóng",
  "paySettingsVenueSelect": "Chọn địa điểm",

  // ── Player Discounts ────────────────────────────────────────────────────────
  "playerDiscountTitle": "Giảm giá người chơi",
  "playerDiscountEmpty": "Chưa có giảm giá nào",
  "playerDiscountAdd": "Thêm giảm giá",
  "playerDiscountDeleteConfirm": "Xoá giảm giá cho người chơi này?",
  "playerDiscountEditTitle": "Sửa giảm giá",
  "playerDiscountCreateTitle": "Tạo giảm giá",
  "playerDiscountSearchPlaceholder": "Tìm người chơi theo tên hoặc SĐT...",
  "playerDiscountNoResults": "Không tìm thấy",
  "playerDiscountChange": "Đổi",
  "playerDiscountFixed": "Giá cố định",
  "playerDiscountPercent": "Phần trăm",
  "playerDiscountCustomFeeLabel": "Giá tuỳ chỉnh (VND)",
  "playerDiscountDefaultFee": "Mặc định: {{fee}} VND",
  "playerDiscountPctLabel": "Giảm giá %",
  "playerDiscountPctResult": "Người chơi trả: {{price}} VND",
  "playerDiscountNoteLabel": "Ghi chú (tuỳ chọn)",
  "playerDiscountNotePlaceholder": "VD: HLV, Thường xuyên, Bạn bè...",
  "playerDiscountSave": "Lưu",
  "playerDiscountSaveError": "Lỗi lưu giảm giá",
  "playerDiscountDelete": "Xoá",
  "playerDiscountCancel": "Huỷ",

  // ── Reclub KPIs ─────────────────────────────────────────────────────────────
  "reclubKpiMatched": "Khớp",
  "reclubKpiAbsent": "Vắng",
  "reclubKpiWalkIn": "Walk-in",
  "reclubKpiBooked": "Đã đặt",
  "reclubKpiPaid": "Đã trả",
  "reclubKpiUnmatched": "Chưa khớp",
  "reclubKpiExpected": "Chờ đến",

  // ── Reclub Roster / Session Detail ──────────────────────────────────────────
  "reclubFetchRoster": "Tải danh sách Reclub",
  "reclubNoEvents": "Hôm nay không có sự kiện Reclub. Phiên CourtPay hoạt động bình thường.",
  "reclubLegendTitle": "Chú thích",
  "reclubLegendMatchedPaid": "Khớp & đã trả",
  "reclubLegendAbsent": "Vắng mặt",
  "reclubLegendWalkIn": "Walk-in",
  "reclubTabPayments": "Thanh toán",
  "reclubTabReclub": "Reclub",
  "reclubNoSnapshot": "Không có dữ liệu Reclub cho phiên này.",
  "reclubNoSnapshotHint": "Snapshot sẽ được tạo khi đóng phiên có roster Reclub.",

  // ── Boss Dashboard ─────────────────────────────────────────────────────────
  "bossDashboardTitle": "Bảng Boss",
  "bossDashboardTabToday": "Hôm nay",
  "bossDashboardTabHistory": "Lịch sử",
  "bossDashboardTabSubs": "Gói",
  "bossDashboardTabPlayers": "Người chơi",
  "bossDashboardTabBilling": "Thanh toán",
  "bossDashboardSessionPayments": "Số lượng thanh toán",
  "bossDashboardRevenue": "Doanh thu",
  "bossDashboardSubscribers": "Thành viên",
  "bossDashboardPending": "Đang chờ",
  "bossDashboardTodaySessions": "Buổi hôm nay",
  "bossDashboardNoSessions": "Không có buổi hôm nay.",
  "bossDashboardRevenueSummary": "Tóm tắt doanh thu",
  "bossDashboardToday": "Hôm nay",
  "bossDashboardYesterday": "Hôm qua",
  "bossDashboardThisWeek": "Tuần này",
  "bossDashboardThisMonth": "Tháng này",
  "bossDashboardAllTime": "Toàn thời gian",
  "bossDashboardPayments": "thanh toán",
  "bossDashboardDailyRevenue": "Doanh thu theo ngày (tất cả thanh toán hôm nay)",
  "bossDashboardPastSessions": "Buổi trước",
  "bossDashboardSessionPlayersPaid": "người",
  "bossDashboardNoPastSessions": "Không có buổi nào.",
  "bossDashboardTotalPlayers": "Tổng người chơi",
  "bossDashboardNewThisWeek": "Mới tuần này",
  "bossDashboardWithSubscription": "Có gói thành viên",
  "bossDashboardAvgReturn": "Ngày quay lại TB",
  "bossDashboardAvgVisits": "Lượt thăm TB / người",
  "bossDashboardReturned": "Quay lại (15 ngày) %",
  "bossDashboardNoPlayers": "Không tìm thấy người chơi.",
  "bossDashboardLastSeen": "Lần cuối",
  "bossDashboardAvgReturnDays": "ngày quay lại TB",
  "bossDashboardAll": "Tất cả",
  "bossDashboardMale": "Nam",
  "bossDashboardFemale": "Nữ",
  "bossDashboardSearchPlaceholder": "Tìm theo tên hoặc SĐT…",
  "bossDashboardBillingThisWeek": "Tuần này",
  "bossDashboardBillingPayments": "Thanh toán",
  "bossDashboardBillingBase": "Cơ bản",
  "bossDashboardBillingSubPayments": "Thanh toán gói thành viên",
  "bossDashboardBillingSubAddon": "Phí thêm",
  "bossDashboardBillingAutoPayment": "Tự động xác nhận",
  "bossDashboardBillingEstimated": "Ước tính tổng",
  "bossDashboardBillingTapView": "Nhấn để xem thanh toán tuần.",
  "bossDashboardBillingPastWeeks": "Tuần trước",
  "bossDashboardBillingNoBilling": "Chưa có dữ liệu thanh toán",
  "bossDashboardBillingWeekPaid": "✓ Tuần đã thanh toán",
  "bossDashboardBillingOverdue": "Hóa đơn quá hạn ⚠️",
  "bossDashboardBillingDue": "Hóa đơn đến hạn ⏳",
  "bossDashboardBillingTotalPayments": "Tổng thanh toán",
  "bossDashboardBillingBaseCharges": "Phí cơ bản",
  "bossDashboardBillingSubAddonLabel": "Phí thêm gói thành viên",
  "bossDashboardBillingAutoPayAddon": "Phí thêm tự động thanh toán",
  "bossDashboardBillingTotal": "Tổng",
  "bossDashboardBillingPaid": "Đã thanh toán",
  "bossDashboardBillingTapCollapse": "Nhấn để thu gọn",
  "bossDashboardBillingTapDetails": "✓ Nhấn để xem chi tiết",
  "bossDashboardBillingPayNow": "Thanh toán ngay — quét QR ▼",
  "bossDashboardBillingHideQR": "Ẩn QR ▲",
  "bossDashboardBillingAmount": "Số tiền",
  "bossDashboardBillingRef": "Mã tham chiếu",
  "bossDashboardBillingAutoConfirm": "Thanh toán tự động xác nhận khi nhận được",
  "bossDashboardBillingWaiting": "Đang chờ thanh toán...",
  "bossDashboardBillingPaymentReceived": "Đã nhận thanh toán — cảm ơn!",
  "bossDashboardBillingNoQR": "Không thể tạo mã QR",
  "bossDashboardClosed": "đã đóng",
  "bossExportRevenueTitle": "Xuất doanh thu (CSV)",
  "bossExportFrom": "Từ ngày",
  "bossExportTo": "Đến ngày",
  "bossExportButton": "Xuất",
  "bossExportCancel": "Hủy",
  "bossExportPreparing": "Đang chuẩn bị xuất…",
  "bossExportNoData": "Không có buổi trong khoảng ngày này.",
  "bossExportInvalidRange": "Ngày bắt đầu phải trước hoặc bằng ngày kết thúc.",
  "sessionDetailExportCsv": "Xuất CSV buổi",

  // ── Staff Dashboard ────────────────────────────────────────────────────────
  "staffDashboardTitle": "Bảng điều khiển nhân viên",
  "staffDashboardTabSubscribers": "Thành viên",
  "staffDashboardTabPlayers": "Người chơi",
  "staffDashboardTotalPlayers": "Tổng người chơi",
  "staffDashboardNewThisWeek": "Mới tuần này",
  "staffDashboardWithSub": "Có gói thành viên",
  "staffDashboardAvgVisits": "Lượt thăm TB / người",
  "staffDashboardNoPlayers": "Không tìm thấy người chơi.",
  "staffDashboardLastSeen": "Lần cuối",
  "staffDashboardVisits": "lượt",
  "staffDashboardShareTitle": "Chia sẻ link kiểm tra số dư",
  "staffDashboardShareDesc": "Người chơi có thể kiểm tra số dư buổi mà không cần cài ứng dụng.",
  "staffDashboardShareBtn": "Chia sẻ link & QR",
  "staffDashboardShareModalTitle": "Chia sẻ kiểm tra số dư",
  "staffDashboardShareModalDesc": "Gửi link này cho người chơi để họ có thể kiểm tra số dư buổi bất cứ lúc nào — không cần ứng dụng.",
  "staffDashboardShareModalClose": "Đóng",
  "staffDashboardShareModalShare": "Chia sẻ link & QR",

  // ── Subscriptions screen ────────────────────────────────────────────────────
  "subsTitle": "Gói thành viên",
  "subsTabPackages": "Gói",
  "subsTabSubscribers": "Thành viên",
  "subsShowInFlow": "Hiển thị trong quy trình CourtPay",
  "subsShowInFlowDesc": "Khi tắt, người chơi đi thẳng đến thanh toán một buổi và bỏ qua màn hình gói.",
  "subsNoPackages": "Chưa có gói nào",
  "subsCreateForMe": "Tạo gói cho tôi",
  "subsCreateCustom": "hoặc tạo gói tùy chỉnh",
  "subsAddPackage": "Thêm gói",
  "subsMaxReached": "Đã đạt tối đa {{max}} gói hoạt động.",
  "subsBestChoice": "Lựa chọn tốt nhất",
  "subsSave": "Tiết kiệm {{pct}}%",
  "subsUnlimitedSessions": "Không giới hạn buổi",
  "subsSessions": "buổi",
  "subsActiveSubs": "Thành viên đang dùng",
  "subsDays": "ngày",
  "subsEdit": "Sửa",
  "subsDelete": "Xóa",
  "subsModalCreateTitle": "Tạo gói",
  "subsModalEditTitle": "Sửa gói",
  "subsPackageName": "Tên gói",
  "subsPackageNamePlaceholder": "Ví dụ: Gói tháng",
  "subsSessionsIncluded": "Số buổi",
  "subsUnlimited": "Không giới hạn",
  "subsValidDays": "Hiệu lực (ngày)",
  "subsPriceVND": "Giá (VND)",
  "subsDiscountPct": "Giảm giá (%)",
  "subsPerks": "Ưu đãi (tùy chọn)",
  "subsCancel": "Hủy",
  "subsSaveBtn": "Lưu",
  "subsShareTitle": "Chia sẻ link kiểm tra số dư",
  "subsShareDesc": "Người chơi có thể kiểm tra số dư buổi mà không cần cài ứng dụng.",
  "subsShareBtn": "Chia sẻ link & QR",
  "subsShareModalTitle": "Chia sẻ kiểm tra số dư",
  "subsShareModalDesc": "Gửi link này cho người chơi để họ có thể kiểm tra số dư buổi bất cứ lúc nào — không cần ứng dụng.",
  "subsShareModalClose": "Đóng",
  "subsShareModalShare": "Chia sẻ",

  // ── Continue As (role select) screen ───────────────────────────────────────
  "continueAsTitle": "Tiếp tục với tư cách",
  "continueAsSubtitle": "Chọn vai trò của bạn để bắt đầu",
  "continueAsWelcome": "Chào mừng",
  "continueAsSignOut": "Đăng xuất",
  "continueAsStaffLabel": "Bảng nhân viên",
  "continueAsStaffDesc": "Quản lý buổi, điểm danh và thanh toán",
  "continueAsAdminLabel": "Quản trị viên",
  "continueAsAdminDesc": "Bảng quản trị đầy đủ (web view)",
  "continueAsTabletLabel": "Chế độ Tablet",
  "continueAsTabletDesc": "Tự điểm danh hoặc kiosk CourtPay",
  "continueAsLogOutTitle": "Đăng xuất",
  "continueAsLogOutMsg": "Bạn có chắc không?",
  "continueAsAccessRestricted": "Truy cập bị hạn chế",
  "continueAsAccessRestrictedMsg": "Chỉ tài khoản quản trị mới có thể truy cập bảng Admin.",

  // ── Boss Subscription Detail ────────────────────────────────────────────────
  "bossSubDetailTitle": "Chi tiết gói thành viên",
  "bossSubDetailPurchased": "Ngày mua",
  "bossSubDetailExpires": "Hết hạn",
  "bossSubDetailLastCheckIn": "Điểm danh gần nhất",
  "bossSubDetailUsed": "đã dùng",
  "bossSubDetailCheckInHistory": "Lịch sử điểm danh",
  "bossSubDetailNoCheckIns": "Chưa có lần điểm danh nào.",
  "bossSubDetailRetry": "Thử lại",
  "bossSubDetailNotFound": "Không tìm thấy gói thành viên",
  "bossSubDetailUnlimited": "Không giới hạn"
} as const;

export const TABLET_ARIA: Record<TabletKioskLocale, { switchToEnglishAria: string; switchToVietnameseAria: string }> = {
  en: {"switchToEnglishAria":"Switch language to English","switchToVietnameseAria":"Switch language to Vietnamese"},
  vi: {"switchToEnglishAria":"Chuyển sang tiếng Anh","switchToVietnameseAria":"Chuyển sang tiếng Việt"},
};

function interpolate(template: string, params?: Record<string, string | number>): string {
  if (!params) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (_, k: string) =>
    params[k] !== undefined && params[k] !== null ? String(params[k]) : ""
  );
}

export function checkInScannerT(
  locale: TabletKioskLocale,
  key: CheckInScannerStringKey,
  params?: Record<string, string | number>
): string {
  const table = locale === "vi" ? CHECK_IN_SCANNER_VI : CHECK_IN_SCANNER_EN;
  const raw = table[key as keyof typeof table];
  if (typeof raw !== "string") return String(key);
  return interpolate(raw, params);
}
