/* Strings mirror PWA `src/i18n/locales/tv/en.json` / `vi.json` (tablet.checkInScanner) plus a few RN-only keys. */
import type { TabletKioskLocale } from "./tablet-kiosk-locale";

export type CheckInScannerStringKey = keyof typeof CHECK_IN_SCANNER_EN;

const CHECK_IN_SCANNER_EN = {
  "welcomeTitle": "Welcome!",
  "tapToCheckIn": "Tap below to check in",
  "checkIn": "Check In",
  "checkInWithPhone": "Check in with phone",
  "faceHint": "The camera will scan your face to check you in.",
  "noMatchYet": "No match yet — adjust if needed",
  "positionFace": "Position your face — scanning starts in a moment",
  "holdStill": "Hold still — scanning now",
  "nextScanIn": "Next scan in",
  "scanning": "Scanning...",
  "retryAuto": "We'll try again automatically",
  "cameraReady": "Camera ready",
  "noFaceDetected": "No face detected",
  "somethingWrong": "Something went wrong",
  "lookAtCamera": "Look at the camera and try again",
  "tryAgain": "Please try again",
  "faceNotRecognized": "Face not recognised",
  "faceNotRecognizedHint": "Try checking in with your phone number, or scan again",
  "scanAgain": "Scan Again",
  "networkShowingLast": "Network issue — showing last check-in",
  "offlineSync": "Offline — will sync when network returns",
  "networkIssue": "Network issue",
  "seeStaff": "See staff for check-in",
  "checkInByPhone": "Check in by phone",
  "enterPhonePrompt": "Enter your phone number",
  "enterPhone": "Enter a phone number",
  "phonePlaceholder": "Phone number",
  "lookUp": "Look up",
  "phoneLabel": "Phone:",
  "levelLabel": "Level:",
  "alreadyCheckedIn": "Already checked in",
  "confirmCheckIn": "Confirm check-in",
  "homeCheckIn": "Check In",
  "homeCheckInSub": "I've played here before",
  "homeFirstTime": "First Time?",
  "homeFirstTimeSub": "Register & pay to play",
  "regTitle": "Let's set up your profile",
  "regFaceHint": "First, look at the camera",
  "regGotPhoto": "Got your photo!",
  "regLooksGood": "Looks good",
  "regRetake": "Retake",
  "regName": "Name",
  "regNamePlaceholder": "Your name",
  "regPhone": "Phone number",
  "regPhonePlaceholder": "Your phone number",
  "regGender": "Gender",
  "regMale": "Male",
  "regFemale": "Female",
  "regLevel": "Level",
  "regBeginner": "Beginner",
  "regBeginnerDesc": "New to pickleball",
  "regIntermediate": "Intermediate",
  "regIntermediateDesc": "Know the rules, can rally",
  "regAdvanced": "Advanced",
  "regAdvancedDesc": "Competitive play",
  "regExistingUserTitle": "Existing user",
  "regExistingUserHint": "This face is already registered. Please use Check In.",
  "regNext": "Next",
  "payTitle": "Almost there, {{name}}!",
  "payReturningTitle": "Payment",
  "payScanQR": "Scan with your banking app then show staff to confirm",
  "payOr": "or",
  "payByCash": "Pay by cash",
  "payCashHint": "Tell staff you're paying cash",
  "payCashTitle": "Please pay {{amount}} cash to staff to complete check-in",
  "payWaitingForStaff": "Waiting for staff to confirm",
  "payTimeout": "Payment not confirmed",
  "payTimeoutHint": "Please show your payment to staff",
  "payCancelled": "Payment was not confirmed",
  "payCancelledHint": "Please see staff at the desk",
  "payNetworkError": "Connection issue",
  "payNetworkErrorHint": "Please see staff",
  "noActiveSession": "No session running right now",
  "noActiveSessionHint": "Please see staff",
  "regAlreadyRegistered": "You're already registered! Use Check In instead.",
  "regPhoneExists": "This phone number is already registered. Use Check In instead.",
  "successWelcomeBack": "Welcome back, {{name}}!",
  "successWelcomeNew": "Welcome to {{venue}}, {{name}}!",
  "successFaceRegistered": "Your face is registered — next time just scan to check in",
  "successHeadToTv": "When you're ready to play scan your face at the TV screen",
  "enterWristband": "Enter wristband number",
  "wristbandPlaceholder": "Wristband #",
  "wristbandLookUp": "Look up",
  "returningToMenu": "Returning to menu in {{seconds}}s…",
  "done": "Done",
  "cancel": "Cancel",
  "back": "Back",
  "backToHome": "Back to Home",
  "cameraPermissionTitle": "Camera access",
  "cameraPermissionHint": "Allow the camera to take your registration photo.",
  "allowCameraCta": "Allow Camera",
  "cameraStarting": "Starting camera…",
  "checkInComplete": "Check-in complete.",
  "registrationComplete": "Registration complete.",
  "cashPaymentConfirmed": "Cash payment confirmed.",
  "paymentConfirmed": "Payment confirmed.",
  "usePhoneInstead": "Use phone number instead",
  "tryAgainGeneric": "Try again",
  "registerAndContinue": "Register & Continue",
  "yourDetails": "Your details",
  "fullNamePlaceholder": "Full name",
  "scanToPay": "Scan to Pay",
  "waitingForPayment": "Waiting for payment…",
  "welcomeExclaim": "Welcome!",
  "kioskTagline": "More gameplay, more fun"
} as const;

const CHECK_IN_SCANNER_VI = {
  "welcomeTitle": "Chào mừng!",
  "tapToCheckIn": "Nhấn bên dưới để check-in",
  "checkIn": "Điểm danh",
  "checkInWithPhone": "Điểm danh bằng số điện thoại",
  "faceHint": "Camera sẽ quét khuôn mặt để check-in cho bạn.",
  "noMatchYet": "Chưa nhận diện được — điều chỉnh lại nếu cần",
  "positionFace": "Đặt khuôn mặt vào khung — sẽ quét ngay",
  "holdStill": "Giữ yên — đang quét",
  "nextScanIn": "Lần quét tiếp theo sau",
  "scanning": "Đang quét...",
  "retryAuto": "Hệ thống sẽ tự quét lại",
  "cameraReady": "Camera sẵn sàng",
  "noFaceDetected": "Không phát hiện khuôn mặt",
  "somethingWrong": "Đã có lỗi xảy ra",
  "lookAtCamera": "Nhìn vào camera và thử lại",
  "tryAgain": "Vui lòng thử lại",
  "faceNotRecognized": "Không nhận diện được khuôn mặt",
  "faceNotRecognizedHint": "Hãy check-in bằng số điện thoại, hoặc quét lại",
  "scanAgain": "Quét lại",
  "networkShowingLast": "Lỗi mạng — đang hiển thị lần check-in gần nhất",
  "offlineSync": "Đang offline — sẽ đồng bộ khi có mạng",
  "networkIssue": "Lỗi mạng",
  "seeStaff": "Liên hệ nhân viên để check-in",
  "checkInByPhone": "Điểm danh bằng điện thoại",
  "enterPhonePrompt": "Nhập số điện thoại của bạn",
  "enterPhone": "Nhập số điện thoại",
  "phonePlaceholder": "Số điện thoại",
  "lookUp": "Tra cứu",
  "phoneLabel": "Điện thoại:",
  "levelLabel": "Trình độ:",
  "alreadyCheckedIn": "Đã check-in",
  "confirmCheckIn": "Xác nhận điểm danh",
  "homeCheckIn": "Điểm danh",
  "homeCheckInSub": "Tôi đã chơi ở đây trước",
  "homeFirstTime": "Lần đầu?",
  "homeFirstTimeSub": "Đăng ký & thanh toán",
  "regTitle": "Tạo hồ sơ của bạn",
  "regFaceHint": "Trước tiên, nhìn vào camera",
  "regGotPhoto": "Đã chụp ảnh!",
  "regLooksGood": "Được rồi",
  "regRetake": "Chụp lại",
  "regName": "Tên",
  "regNamePlaceholder": "Tên của bạn",
  "regPhone": "Số điện thoại",
  "regPhonePlaceholder": "Số điện thoại của bạn",
  "regGender": "Giới tính",
  "regMale": "Nam",
  "regFemale": "Nữ",
  "regLevel": "Trình độ",
  "regBeginner": "Mới chơi",
  "regBeginnerDesc": "Mới chơi pickleball",
  "regIntermediate": "Trung bình",
  "regIntermediateDesc": "Biết luật, đánh được",
  "regAdvanced": "Khá",
  "regAdvancedDesc": "Chơi thi đấu",
  "regExistingUserTitle": "Người dùng đã tồn tại",
  "regExistingUserHint": "Khuôn mặt này đã được đăng ký. Vui lòng dùng Điểm danh.",
  "regNext": "Tiếp",
  "payTitle": "Sắp xong rồi, {{name}}!",
  "payReturningTitle": "Thanh toán",
  "payScanQR": "Quét bằng ứng dụng ngân hàng rồi cho nhân viên xác nhận",
  "payOr": "hoặc",
  "payByCash": "Trả tiền mặt",
  "payCashHint": "Báo nhân viên bạn trả tiền mặt",
  "payCashTitle": "Vui lòng trả {{amount}} tiền mặt cho nhân viên",
  "payWaitingForStaff": "Đang chờ nhân viên xác nhận",
  "payTimeout": "Chưa xác nhận thanh toán",
  "payTimeoutHint": "Vui lòng cho nhân viên xem thanh toán",
  "payCancelled": "Thanh toán chưa được xác nhận",
  "payCancelledHint": "Vui lòng gặp nhân viên",
  "payNetworkError": "Lỗi kết nối",
  "payNetworkErrorHint": "Vui lòng gặp nhân viên",
  "noActiveSession": "Hiện không có phiên nào",
  "noActiveSessionHint": "Vui lòng gặp nhân viên",
  "regAlreadyRegistered": "Bạn đã đăng ký rồi! Hãy dùng Điểm danh.",
  "regPhoneExists": "Số điện thoại này đã được đăng ký. Hãy dùng Điểm danh.",
  "successWelcomeBack": "Chào mừng trở lại, {{name}}!",
  "successWelcomeNew": "Chào mừng đến {{venue}}, {{name}}!",
  "successFaceRegistered": "Khuôn mặt đã được đăng ký — lần sau chỉ cần quét để check-in",
  "successHeadToTv": "Khi sẵn sàng chơi hãy quét khuôn mặt tại màn hình TV",
  "enterWristband": "Nhập số vòng tay",
  "wristbandPlaceholder": "Số vòng tay",
  "wristbandLookUp": "Tra cứu",
  "returningToMenu": "Quay lại menu sau {{seconds}} giây…",
  "done": "Xong",
  "cancel": "Hủy",
  "back": "Quay lại",
  "backToHome": "Về trang chủ",
  "cameraPermissionTitle": "Quyền truy cập camera",
  "cameraPermissionHint": "Cho phép camera để chụp ảnh đăng ký.",
  "allowCameraCta": "Cho phép camera",
  "cameraStarting": "Đang khởi động camera…",
  "checkInComplete": "Check-in hoàn tất.",
  "registrationComplete": "Đăng ký hoàn tất.",
  "cashPaymentConfirmed": "Đã xác nhận thanh toán tiền mặt.",
  "paymentConfirmed": "Đã xác nhận thanh toán.",
  "usePhoneInstead": "Dùng số điện thoại thay thế",
  "tryAgainGeneric": "Thử lại",
  "registerAndContinue": "Đăng ký & tiếp tục",
  "yourDetails": "Thông tin của bạn",
  "fullNamePlaceholder": "Họ và tên",
  "scanToPay": "Quét để thanh toán",
  "waitingForPayment": "Đang chờ thanh toán…",
  "welcomeExclaim": "Chào mừng!",
  "kioskTagline": "Nhiều trận hơn, nhiều niềm vui hơn"
} as const;

export const TABLET_ARIA: Record<TabletKioskLocale, { switchToEnglishAria: string; switchToVietnameseAria: string }> = {
  en: {"switchToEnglishAria":"Switch language to English","switchToVietnameseAria":"Switch language to Vietnamese"},
  vi: {"switchToEnglishAria":"Chuyển sang tiếng Anh","switchToVietnameseAria":"Chuyển sang tiếng Việt"},
};

function interpolate(template: string, params?: Record<string, string | number>): string {
  if (!params) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (_, k: string) =>
    params[k] !== undefined && params[k] !== null ? String(params[k]) : ""
  );
}

export function checkInScannerT(
  locale: TabletKioskLocale,
  key: CheckInScannerStringKey,
  params?: Record<string, string | number>
): string {
  const table = locale === "vi" ? CHECK_IN_SCANNER_VI : CHECK_IN_SCANNER_EN;
  const raw = table[key as keyof typeof table];
  if (typeof raw !== "string") return String(key);
  return interpolate(raw, params);
}
